title: Shuo Lei
position: Research Scientist
affiliation: Sony Research
email: shuo.lei (at) sony.com
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=vm368LkAAAAJ&hl=en
github_link: https://github.com/slei109
linkedin: www.linkedin.com/in/slei109
avatar: ./assets/img/Shuo_latest.jpeg
#google_analytics: UA-111540567-4
favicon: ./assets/img/ls_logo.png
favicon_dark: ./assets/img/ls_logo.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
#canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
